// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn3v8TZ3pdrPy3LBu0H_90-IEuq0OxxHo',
    appId: '1:78531065035:web:cdf78e739191e3bcd1974e',
    messagingSenderId: '78531065035',
    projectId: 'keeley-mobile',
    authDomain: 'keeley-mobile.firebaseapp.com',
    storageBucket: 'keeley-mobile.firebasestorage.app',
    measurementId: 'G-CH036WSS8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwKWZi0zAhfbx1W2jvXtD6mqEUGfU1FzU',
    appId: '1:78531065035:android:96d86bc20ef78ab6d1974e',
    messagingSenderId: '78531065035',
    projectId: 'keeley-mobile',
    storageBucket: 'keeley-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf1VUmmjL8kNE639I1AHwAYAxllzg_kfQ',
    appId: '1:78531065035:ios:a95b5010231417cfd1974e',
    messagingSenderId: '78531065035',
    projectId: 'keeley-mobile',
    storageBucket: 'keeley-mobile.firebasestorage.app',
    iosBundleId: 'com.example.keeley',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf1VUmmjL8kNE639I1AHwAYAxllzg_kfQ',
    appId: '1:78531065035:ios:a95b5010231417cfd1974e',
    messagingSenderId: '78531065035',
    projectId: 'keeley-mobile',
    storageBucket: 'keeley-mobile.firebasestorage.app',
    iosBundleId: 'com.example.keeley',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn3v8TZ3pdrPy3LBu0H_90-IEuq0OxxHo',
    appId: '1:78531065035:web:d7926aa6b9d1f0ded1974e',
    messagingSenderId: '78531065035',
    projectId: 'keeley-mobile',
    authDomain: 'keeley-mobile.firebaseapp.com',
    storageBucket: 'keeley-mobile.firebasestorage.app',
    measurementId: 'G-K0MKY7640Q',
  );
}
